version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: autoconnect_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - '3306'
        networks:
            - tutorial

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: autoconnect_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
        networks:
            - tutorial

    # laravel apache project container
    www:
        build: docker/php
        container_name: autoconnect_app
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/html
        restart: always
        networks:
            - tutorial

networks:
    tutorial:

volumes:
    db-data: